[project]
name = "dirtdash"
version = "0.1.0a1"
description = "Real-time DiRT Rally 2.0 telemetry dashboard (UDP Extradata=3)"
readme = "README.md"
license = "GPL-3.0-only"
requires-python = ">=3.12"
authors = [{ name = "Alperen (alpivenator)" }]
dependencies = ["pygame"]

[project.optional-dependencies]
pi = ["gpiozero==2.0.1"]

# Black tool configuration
[tool.black]
line-length = 90 # Maximum allowed line length
target-version = ['py312'] # Target Python version for code optimization

# Ruff tool configuration
[tool.ruff]
line-length = 90 # Keep Ruff's line limit consistent with Black
lint.select = ["E", "F", "I"] # E (Errors), F (Logic Errors), I (Import sorting rules)
